### ISSUE TITLE
Create releases with pre-compiled binaries

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/dotenv-hs#112]
`dotenv` is meant to be used as an executable, therefore, in order to simplify the installation process, we could provide pre-compiled binaries so end-users could just download and copy the binary instead of installing the whole package via `stack` or `cabal`.

**Documentation**
- https://help.github.com/en/github/administering-a-repository/creating-releases
- https://docs.travis-ci.com/user/deployment/releases/

**References**
- https://github.com/commercialhaskell/stack/releases

**Comment by CristhianMotoche** [comment]
I've never done this before. I'd love to take this.

**Comment by CristhianMotoche** [comment]
Hey @sestrella As we discussed, let's do this step incrementally. I think our final goal is to make `dotenv` binary work for the following operating systems:
- [ ] Linux x86_64
- [ ] Mac osX
- [ ] Windows

I'll keep you updated with any progress.

**Comment by sestrella** [comment]
@CristhianMotoche sounds good to me, thank you for carrying this on.

**Comment by CristhianMotoche** [comment]
@sestrella I'm trying to set the release notes. Here is my first attempt: https://github.com/stackbuilders/dotenv-hs/releases/tag/untagged-8972a8d79f11a59c973f

Two things here:

1) The advanced options of [travis deploy didn't work](https://docs.travis-ci.com/user/deployment/releases/#advanced-options), because [formatting the `body` isn't supported](https://github.com/travis-ci/dpl/issues/155).

2) So, based on this [issue](https://github.com/travis-ci/dpl/issues/155), I followed the suggestion described [here](https://github.com/travis-ci/dpl/issues/155#issuecomment-500130415).

Let me know what you think.

**Comment by CristhianMotoche** [comment]
Travis has the option to build on Mac OS and even Windows, I think. However, it cannot collect artifacts after builds. Info [here](https://docs.travis-ci.com/user/build-stages/#data-persistence-between-stages-and-jobs). An option that Travis suggests is to set up a S3 bucket and push the artifacts there. And later, move those binaries from S3 to a GitHub release.

What do you think about that approach? /cc @sestrella @juanpaucar

**Comment by sestrella** [comment]
@CristhianMotoche nice suggestion, in fact, that seems to be the way to go in some well-know packages such as [stack](https://github.com/commercialhaskell/stack/tree/master/etc/scripts). I think adding some deployment scripts - to build the binaries locally - would be a good idea.
